export const keywords = [
  "Duda",
  "Morawiecki",
  "Kaczyński",
  "Tusk",
  "Czarnek",
  "Godek",
  "Kwaśniewski",
  "Wałęsa",
  "Petru",
  "Staroń",
  "Korwin-Mikke",
  "Kukiz",
  "Sasin",
  "Zandberg",
  "Biedroń",
  "Braun",
  "Bosak",
  "Palikot",
  "Stonoga",
  "Ziobro",
  "Hołownia",
  "Lisiecki",
];

export const rewards = [
  "Ultimate nagroda - średniej wielkości przysługa",
  "Zamówię Ci pizzę z dowozem",
  "Zdjęcie z dowolnym kotem na profil Samsonjebaka",
  "Twoje zdjęcie do dowodu obok naszych na Białej",
  "Zaproszenie na wieczór gier ze mną (lub nie) i solenizatnką",
  "Zaproszenie na piwo ze mną (lub nie) i solenizantką",
  "Zaproszenie na obiad ze mną (lub nie) i solenizantką",
  "Mozliwość mieszkania ze mna w następnej edycji serwera minecraft",
  "Kasztelan",
  "Kasztelan",
  "Kasztelan",
  "Kasztelan",
  "Kasztelan",
  "Kasztelan",
  "Kasztelan",
  "Kasztelan",
  "Nic",
  "Nic",
  "Nic",
  "Nic",
  "Nic",
  "Wpierdol",
];
